name: Deploy into production server

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy at remote server
        uses: appleboy/ssh-action@master
        with:
          host:     ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key:      ${{ secrets.SSH_KEY }}
          port:     ${{ secrets.SSH_PORT }}
          envs: DIR
          script_stop: true
          script: |
            source .bashrc
            cd $DIR

            # .git directoryがなければcloneする
            if [ ! -d .git ]; then
              git init
              git remote add origin https://github.com/shingo119/deploy-test-html.git
            fi

            git pull origin main
        env:
          DIR: public_html/deploy-test-html.com
